// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAn3OV1zRoEx5T4pA6VY6kkDl2APQNIAQ',
    appId: '1:695942497491:web:d63a4097532767cfcec026',
    messagingSenderId: '695942497491',
    projectId: 'quizapp-1b3b4',
    authDomain: 'quizapp-1b3b4.firebaseapp.com',
    storageBucket: 'quizapp-1b3b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5flfAh6FgZ3XqtIYbwt8aKZqiA2mtv0',
    appId: '1:695942497491:android:b03a6baa6c382727cec026',
    messagingSenderId: '695942497491',
    projectId: 'quizapp-1b3b4',
    storageBucket: 'quizapp-1b3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyT2kht3V1yMl_eKVqliXi1k8Xejfggc',
    appId: '1:695942497491:ios:d66332e0324ac972cec026',
    messagingSenderId: '695942497491',
    projectId: 'quizapp-1b3b4',
    storageBucket: 'quizapp-1b3b4.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );
}
